apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}-config
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  source-tokens.json: |
    {{ mustToJson .Values.tokens }}
