{{- $tlsCert := "" }}
{{- $tlsKey := "" }}
{{- if .Values.tls.enabled }} 
  {{- if .Values.tls.generateSelfSignedCert }}
    {{- $data := (lookup "v1" "Secret" .Release.Namespace (printf "%s-cert" (include "gateway.fullname" . ))).data }}
    {{- if $data }}
      # Reuse the existing cert and key
      {{- $tlsCert = index $data "tls.crt" }}
      {{- $tlsKey = index $data "tls.key" }}
    {{- else }}
      # Generate a new cert and key
      {{- $altName1 := include "gateway.fullname" . }}
      {{- $altName2 := printf "%s.%s" (include "gateway.fullname" .) .Release.Namespace }}
      {{- $altName3 := printf "%s.%s.svc" (include "gateway.fullname" .) .Release.Namespace }}
      {{- $altName4 := printf "%s.%s.svc.cluster" (include "gateway.fullname" .) .Release.Namespace }}
      {{- $altName5 := printf "%s.%s.svc.cluster.local" (include "gateway.fullname" .) .Release.Namespace }}
      {{- $cert := genSelfSignedCert .Values.host nil (list .Values.host $altName1 $altName2 $altName3 $altName4 $altName5) 3650 }}
      {{- $tlsCert = b64enc $cert.Cert }}
      {{- $tlsKey = b64enc $cert.Key }}
    {{- end }}
  {{- else if .Values.tls.cert }}
    # Use operator supplied cert and key
    {{- $tlsCert = .Values.tls.cert }}
    {{- $tlsKey = .Values.tls.key }}
  {{- end }}
{{- end }}
---
{{- if and .Values.tls.enabled (or .Values.tls.generateSelfSignedCert .Values.tls.cert) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}-cert
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
data:
  tls.crt: {{ $tlsCert }}
  tls.key: {{ $tlsKey }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/config-secret: {{ include (print $.Template.BasePath "/config-secret.yaml") . | sha256sum }}
        {{- if and .Values.tls.enabled (or .Values.tls.generateSelfSignedCert .Values.tls.cert) }}
        checksum/tls-cert: {{ sha256sum $tlsCert }}
        checksum/tls-key: {{ sha256sum $tlsKey }}
        {{- end }}
    spec:
      containers:
      - name: gateway
        image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TLS_ENABLED
          value: {{ quote .Values.tls.enabled }}
        {{- if .Values.tls.enabled }}
        - name: TLS_CERT_PATH
          value: /app/certs/tls.crt
        - name: TLS_KEY_PATH
          value: /app/certs/tls.key
        {{- end }}
        - name: API_ADDRESS
          value: {{ .Values.brigade.apiAddress }}
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "gateway.fullname" . }}
              key: brigadeAPIToken
        - name: API_IGNORE_CERT_WARNINGS
          value: {{ quote .Values.brigade.apiIgnoreCertWarnings }}
        - name: SOURCE_TOKENS_PATH
          value: /app/config/source-tokens.json
        volumeMounts:
        - name: config
          mountPath: /app/config
        {{- if .Values.tls.enabled }}
        - name: cert
          mountPath: /app/certs
          readOnly: true
        {{- end }}
        livenessProbe:
          httpGet:
            port: 8080
            path: /healthz
            {{- if .Values.tls.enabled }}
            scheme: HTTPS
            {{- end }}
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: 8080
            path: /healthz
            {{- if .Values.tls.enabled }}
            scheme: HTTPS
            {{- end }}
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        secret:
          secretName: {{ include "gateway.fullname" . }}-config
      {{- if .Values.tls.enabled }}
      - name: cert
        secret:
          secretName: {{ include "gateway.fullname" . }}-cert
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
